### ISSUE TITLE
Update 1: Kickoff

### ISSUE THREAD

**Issue by gavinmcdermott** [gavinmcdermott/js-libp2p-pstn#1]
Requesting input from @diasdavid  

This weekend I've been working (and next week plan to work) on the test harness. Libp2p has a lot of surface area and supporting libs to understand; today I started moving through it piece by piece. Two things would be really helpful here:

1. Feedback on the initial **plan**
2. Input to some **specific questions** regarding my immediate next steps

### Plan
1. Get the basics working on a local machine 
  * Ability to spin up a few thousand nodes quickly
  * Plus basic tests
2. Add opts for faking more 'real world' network scenarios 
  * E.g.: nodes joining, leaving, etc. (other ideas??)
3. Command line access
4. Docker-ization
5. Kubernetes orchestration

### Specific Questions (_In order of importance_)
**Note: Please add as many comments to this repo's code in response as you'd like. All feedback is welcome**

- **Peer Discover Strategies**: I'd like peer discovery strategies to be configurable (e.g.: `mdns`, `random-walk`, etc.). In the [naive example](https://github.com/gavinmcdermott/pubsub_testnet/blob/master/src/network.js#L43), every node connects to every node. I could be way off here, so some pointing in the right direction will help. To make it concrete, let's take the [mdns sample for example](https://github.com/libp2p/js-libp2p-mdns-discovery/blob/master/examples/example.js):
  * What is `snr` relationship to a libp2p node instance? 
  * How does this interface with the `peerBook`? 
  * Where might that be attached or exposed to work with?

- **Peer Routing**: Similarly, I notice in the [kad-router example](https://github.com/libp2p/js-libp2p-kad-routing/blob/master/tests/router-test.js#L23), that the router works with a peer instance. But I'm curious as to how the `kad-router` (or any peer router) interacts with libp2p nodes.

- **Test Node and Network Interfaces**: Any thoughts on the initial, potential interface we might want to have with respect to:
  * Individual nodes in the testnet (e.g.: `node.goIntermittent()`)
  * The testnet network itself (e.g.: `testnet.triggerOutage({ pct: 30 })`)

I really like the notion of triggering outages, latency, node drops and joins. But those can also come in once the basics are working. Just want to get initial thoughts out there.

And finally, based on what i'm desiring to do, if you think there's a better question to ask, or something missing, please let me know. Thanks for any feedback!

**Comment by diasdavid** [comment]
Nice work getting this kicked off @gavinmcdermott 👏🏽👏🏽👏🏽👏🏽👏🏽

Let's chat about this on the libp2p hangout today :). Answers to your questions below:

> **Peer Discover Strategies**
>   What is snr relationship to a libp2p node instance?

Probs are sent in an interval (configurable). Not much, udp packets are cheap, and the replied (peer information) are only sent after a broadcast is sent.

> How does this interface with the peerBook?

It doesn't directly. peer-discovery mechanisms have a simple interface -- `.on('peer', doSomething) --, the interface is not formalized yet, but it is like https://github.com/libp2p/js-libp2p-mdns-discovery uses.

> Where might that be attached or exposed to work with?

Inside the libp2p build (libp2p enables the dev to create several flavors of it, depending on their requirements), check libp2p-ipfs-browser, the browser build of js-ipfs, there we use the discovery mechanism offered by the WebRTC Transport (webrtc-star) to find other peers -> https://github.com/ipfs/js-libp2p-ipfs-browser/blob/master/src/index.js#L57-L59

In this example, we pass the responsibility to js-ipfs to decide what to do with the peer. (what js-ipfs does is ensuring it can dial and if so, add it to the PeerBook)

> Peer Routing: Similarly, I notice in the kad-router example, that the router works with a peer instance. But I'm curious as to how the kad-router (or any peer router) interacts with libp2p nodes.

Peer Routing is a mechanism to 'find peers', the interface is designed to offer a dumb "find peers with this/for this id and returns PeerInfos that can be used to dial (it is expected that if a PeerInfo is returned, we can really dial to that peer)

> Test Node and Network Interfaces:

👍👍👍👍👍 to this, it will make creating the tests easier. However, having tests where we actually 'blow up' or throttle the pipes of process will be even better (last mile is getting real hardware to run tests :D)

**Comment by jbenet** [comment]
I think the plan LGTM. May want to think through how the dockerization would work though up front-- may inform (1) and (2).
